//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame_Servidor.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HangmanEntidades : DbContext
    {
        public HangmanEntidades()
            : base("name=HangmanEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<estado_partida> estado_partida { get; set; }
        public virtual DbSet<idioma_partida> idioma_partida { get; set; }
        public virtual DbSet<jugador> jugador { get; set; }
        public virtual DbSet<palabra> palabra { get; set; }
        public virtual DbSet<partida> partida { get; set; }
        public virtual DbSet<resultado> resultado { get; set; }
    }
}
