//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame_Servidor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class palabra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public palabra()
        {
            this.partida = new HashSet<partida>();
        }
    
        public int id_palabra { get; set; }
        public string nombre { get; set; }
        public string nombre_en { get; set; }
        public string pista { get; set; }
        public string descripcion { get; set; }
        public string descripcion_en { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partida> partida { get; set; }
    }
}
