//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGame_Servidor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partida()
        {
            this.resultado = new HashSet<resultado>();
        }
    
        public int id_partida { get; set; }
        public string codigo { get; set; }
        public string idioma { get; set; }
        public Nullable<int> id_palabra { get; set; }
        public Nullable<int> id_retador { get; set; }
        public Nullable<int> id_adivinador { get; set; }
        public Nullable<int> id_estado_partida { get; set; }
        public Nullable<int> id_idioma_partida { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual estado_partida estado_partida { get; set; }
        public virtual idioma_partida idioma_partida { get; set; }
        public virtual jugador jugador { get; set; }
        public virtual jugador jugador1 { get; set; }
        public virtual palabra palabra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resultado> resultado { get; set; }
    }
}
